SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `pregunta` (
  `Id_pregunta` int(11) NOT NULL,
  `pregunta` varchar(160) NOT NULL,
  `respuesta` tinyint(1) NOT NULL,
  `PregxIndi` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `pregunta` (`Id_pregunta`, `pregunta`, `respuesta`, `PregxIndi`) VALUES
(1, '‘Se proyecta hacia una profesión en 10 años?', 0, 1),
(2, '¿Se identifica trabajando en algún establecimiento?', 0, 1),
(3, '¿Quisiera continuar con sus estudios en posteridad?', 0, 1),
(4, '¿Está pensando en adjudicar a alguna entidad educativa?', 0, 1),
(5, '¿Piensa en ingresar a algún instituto militar?', 0, 1),
(6, '¿Después del colegio preferiría trabajar?', 0, 1),
(7, '¿Prefiere las actividades al aire libre?', 0, 2),
(8, '¿Práctica algún deporte?', 0, 2),
(9, '¿Prefiere las canciones suaves a las movidas?', 0, 2),
(10, '¿Dedica parte de su tiempo a leer?', 0, 2),
(11, '¿Piensas dedicar parte de tu tiempo libre a actividades como cocina o culinaria?', 0, 2),
(12, '¿Prefiere la danza antes de la pintura?', 0, 2),
(13, '¿Los juegos de lógica la interesan?', 0, 3),
(14, '¿En su tiempo libre le gusta resolver problemas matemáticos?', 0, 3),
(15, '¿Le gusta realizar ensayos en su asignatura de español?', 0, 3),
(16, '¿Soy bueno (a) en las exposiciones?', 0, 3),
(17, '¿Soy bueno realizando actividades que requieren de coordinación?', 0, 3),
(18, '¿Me gustan los ejercicios que requieren de velocidad y flexibilidad pues considero que soy muy bueno?', 0, 3),
(19, '¿Puedo tocar algún instrumento en mí tiempo libre?', 0, 3),
(20, '¿Prefiero cantar antes de bailar?', 0, 3),
(21, '¿Considero que el ritmo, el tono y la melodía de una canción son importantes?', 0, 3),
(22, '¿Puedo entender las emociones de los demás fácilmente?', 0, 3),
(23, 'Me gusta ponerme en el zapato del otro pues así siento que puedo ayudarlo más', 0, 3),
(24, 'Me considero una persona muy empática con los demás', 0, 3),
(25, 'Conozco mis estados de ánimo y se discernir entre la tristeza y la nostalgia', 0, 3),
(26, 'Considero que tengo conocimiento de lo que soy y quiero ser ', 0, 3),
(27, '¿Cuándo me siento muy triste busco herramientas para que mí estado de ánimo mejore?', 0, 3),
(28, '¿En mí familia las profesiones deben ser las mismas?', 0, 4),
(29, 'Mi familia prefiere que me incline por una carrera del área de la salud', 0, 4),
(30, 'Mis familiares expresan que les gustaría que estudiara una carrera desde el área de artes y humanidades', 0, 4),
(31, 'Mis familiares expresan que debería interesarme por las carreras técnicas o tecnológicas', 0, 4),
(32, 'Mis familiares piensan que las carreras de educación son las más opcionales', 0, 4),
(33, 'Mis familiares prefieren que me dedique a oficios que me permita obtener dinero rápido', 0, 4),
(34, 'Mi familia prefiere profesiones desde el área de la salud', 0, 5),
(35, 'En mí familia lo más importante son las Carreras de ingenierías', 0, 5),
(36, 'En mí familia se prefieren los estudios técnicos o tecnológicos', 0, 5),
(37, 'El estudio universitario es importante para mí familia', 0, 5),
(38, 'Prefiero trabajar a futuro como oficinista', 0, 6),
(39, 'Prefiero el estudio antes que el trabajo', 0, 6),
(40, 'En las actividades de liderazgo me desenvuelvo de manera óptima', 0, 6),
(41, 'Me gusta escuchar y dar mis opiniones acerca de temas sociales', 0, 6),
(42, '¿Trabajaría escribiendo artículos en la sección económica de un diario?', 0, 11),
(43, '¿se ofrecería para organizar fiestas de sus amigos?', 0, 11),
(44, '¿Dirigiría un proyecto de urbanización en la Ciudad u otro lugar?', 0, 11),
(45, '¿Se dedicaría a socorrer a personas en cualquier estado?', 0, 11),
(46, '¿Le interesa saber cómo están construidos los objetos?', 0, 11),
(47, '¿Le interesa el trabajo con la naturaleza?', 0, 11),
(48, '¿Es atento a las problemáticas que suceden en su medio?', 0, 11),
(49, '¿Le gusta explicar a sus compañeros temas de clase que no comprenden?', 0, 11),
(50, '¿Es exigente y crítico con su equipo de trabajo?', 0, 11),
(51, '¿Le atrae armar rompecabezas o puzzles?', 0, 11),
(52, '¿Le interesa la economía o la contabilidad?', 0, 11),
(53, '¿Usar uniforme le hace sentir distinto, importante?', 0, 11),
(54, '¿Preferiría el trabajo con objetos o con personas?', 0, 11),
(55, '¿le atraen los cálculos matemáticos o ciencias exactas?', 0, 11),
(56, '¿Le interesa la agronomía como carrera para estudiar a futuro?', 0, 12),
(57, '¿Tiene conocimientos sobre producción en la actualidad?', 0, 12),
(58, '¿Le gustaría desempeñarse como zootecnista en el futuro?', 0, 12),
(59, '¿se visiona como trabajador del sector productivo?', 0, 12),
(60, '¿Le interesa el trabajo en el campo?', 0, 12),
(61, '¿La naturaleza hace parte de sus intereses?', 0, 12),
(62, '¿Le gustaría trabajar como médico veterinario en el futuro?', 0, 12),
(63, '¿Es su de agrado el trabajo con animales?', 0, 12),
(64, '¿Le interesan las enfermedades o afecciones que presentan los animales?', 0, 12),
(65, '¿Le interesa el bienestar animal?', 0, 12),
(66, '¿El sector agrícola, agrónomo u otro le llaman la atención?', 0, 12),
(67, '¿Le interesa la gestión ambiental?', 0, 12),
(68, '¿Quisiera hacer parte de proyectos de mejoramiento animal?', 0, 12),
(69, '¿Le interesa el tratamiento del suelo y el cultivo?', 0, 12),
(70, '¿Le interesa el aprovechamiento de los recursos del medio?', 0, 12),
(71, '¿Cree que los seres humanos deben basar su vida en valores?', 0, 13),
(72, '¿Está de acuerdo en que los seres humanos deben promover los valores y la solidaridad?', 0, 13),
(73, '¿Piensa que todos los habitantes de este planeta deben ser representantes de la dignidad humana?', 0, 13),
(74, '¿Es más importante la conciencia colectiva que la individual para la toma de decisiones de su contexto?', 0, 13),
(75, '¿Es más importante la conciencia individual que la colectiva para la toma de decisiones en su contexto? ', 0, 13),
(76, '¿La conciencia individual y colectiva tienen la misma importancia para la toma de decisiones en su contexto?', 0, 13),
(77, '¿Se considera bueno en las áreas artísticas?', 0, 13),
(78, '¿Cree usted que es importante la conservación del patrimonio cultural, regional y local en el campo artístico-humanístico?', 0, 13),
(79, '¿Considera que es importante la creación de proyectos sociales para la comunidad de carácter artístico y humanístico?', 0, 13),
(80, '¿Cree que tiene la capacidad para organizar proyectos y actividades novedosas o creativas?', 0, 13),
(81, '¿Tiene interés hacia la investigación?', 0, 13),
(82, '¿Presenta interés y consciencia de los avances científicos con base humanístico que se realizan actualmente?', 0, 13),
(83, '¿Está de acuerdo en que los avances científicos deben contribuir ética y estéticamente a la sociedad?', 0, 13),
(84, '¿Cree que el dialogo en los sectores sociales es importante para mejorar las condiciones y calidad de vida de las comunidades?', 0, 13),
(85, '¿Tiene capacidad para solucionar conflictos que se presentan en su contexto?', 0, 13),
(86, 'Cree usted que tiene deberes éticos con la sociedad y el estado de su país?', 0, 13),
(87, '¿piensa que los valores morales son importantes para la toma de decisiones?', 0, 13),
(88, '¿Para usted la constitución nacional de su país debe ser respetada y cumplida?', 0, 13),
(89, '¿cree que una mentalidad crítica y sensibilidad social dan un aporte significativo para su nación?', 0, 13),
(90, '¿Cree usted que es importante tener conocimientos sobre todas las áreas del saber?', 0, 13),
(91, '¿considera que las escuelas filosóficas dan aportes importantes en la sociedad?', 0, 13),
(92, '¿Cree que es importante que exista una generación que tenga conciencia personal y ciudadana?', 0, 13),
(93, '¿Los seres humanos deberían contribuir a la consolidación, cultivo y respeto por la dignidad de las personas y por el medio ambiente?', 0, 13),
(94, '¿cree que es esencial promover el patrimonio histórico en nuestra sociedad para así fortalecer la identidad local, regional y nacional?', 0, 13),
(95, '¿Posee una excelente redacción y ortografía?', 0, 13),
(96, '¿Tiene usted una buena comprensión lectora?', 0, 13),
(97, '¿Es importante contribuir al mejoramiento constante del arte musical tanto local como regional y nacional?', 0, 13),
(98, '¿Tiene importancia promover y orientar el arte musical?', 0, 13),
(99, '¿El avance científico y al trato humanizante promueve la comprensión a través del arte musical y le da un sentido social y humanitario a la ciencia y ', 0, 13),
(100, '¿Cree usted que es importante la estimulación, el aprendizaje musical, la autoevaluación y la construcción de autoestima, autonomía y responsabilidad?', 0, 13),
(101, '¿Es bueno enseñando?', 0, 14),
(102, '¿Se considera una persona responsable y consciente? ', 0, 14),
(103, '¿Considera que es una persona con valores éticos altos y firmes?', 0, 14),
(104, '¿Es abierto a los cambios que se le presenten?', 0, 14),
(105, '¿Para usted es un tema importante el desarrollo educativo de su país?', 0, 14),
(106, '¿siente interés por aprender nuevos idiomas?', 0, 14),
(107, '¿considera que es importante aprender nuevos idiomas?', 0, 14),
(108, '¿Es bueno en el área de inglés?', 0, 14),
(109, '¿Le gustaría conocer nuevos países?', 0, 14),
(110, '¿Le atrae realizar lectura crítica? ', 0, 14),
(111, '¿Se le facilita la comprensión lectora?', 0, 14),
(112, '¿Le gusta la escritura y ortografía?', 0, 14),
(113, '¿Se considera una persona innovadora?', 0, 14),
(114, '¿Le atrae la investigación de las ciencias sociales y las humanidades?', 0, 14),
(115, '¿Tiene iniciativa por la creación y expansión de la cultura?', 0, 14),
(116, '¿Se considera una persona independiente y racional?', 0, 14),
(117, '¿Le gusta servir a la comunidad?', 0, 14),
(118, '¿Se considera una persona activa o inquieta?', 0, 14),
(119, '¿Le gustan los deportes?', 0, 14),
(120, '¿Le gusta la actividad física?', 0, 14),
(121, '¿Le gusta el baile?', 0, 14),
(122, '¿Tiene la capacidad de autoaprendizaje?', 0, 15),
(123, '¿Se considera una persona de mente abierta?', 0, 15),
(124, '¿Se le facilita trabajar en equipo?', 0, 15),
(125, '¿Es bueno expresando sus ideas?', 0, 15),
(126, '¿Se considera una persona creativa?', 0, 15),
(127, '¿Es una persona innovadora?', 0, 15),
(128, '¿Se considera una persona buena tomando decisiones?', 0, 15),
(129, '¿Es capaz de afrontar las consecuencias de sus decisiones?', 0, 15),
(130, '¿Es capaz de trabajar bajo presión?', 0, 15),
(131, '¿Sabe lidiar con sus emociones?', 0, 15),
(132, '¿Se considera una persona con liderazgo?', 0, 15),
(133, '¿Es una persona minuciosa, con atención a los detalles?', 0, 15),
(134, '¿Cree que es una persona estratégica? ', 0, 15),
(135, '¿Es bueno en matemáticas?', 0, 15),
(136, '¿Considera que tiene amor por la ciencia?', 0, 15),
(137, '¿Es bueno para las diferentes ciencias?', 0, 15),
(138, '¿Es una persona analítica? ', 0, 15),
(139, '¿Se le facilita el análisis de las situaciones?', 0, 15),
(140, '¿Se considera una persona con mente lógica?', 0, 15),
(141, '¿Se toma en serio la educación?', 0, 15),
(142, '¿Le interesa la promoción de la salud?', 0, 16),
(143, '¿Quisiera trabajar en una entidad que preste servicios de salud?', 0, 16),
(144, '¿Le interesa la prevención de enfermedades?', 0, 16),
(145, '¿Le interesan los servicios sociales?', 0, 16),
(146, '¿Le interesa la educación sobre una buena alimentaria?', 0, 16),
(147, '¿Promovería el cambio social?', 0, 16),
(148, '¿Le interesa el conocimiento sobre el ser humano en general?', 0, 16),
(149, '¿Le interesa el estudio de la vida y de la salud?', 0, 16),
(150, '¿Le interesa estudiar la prevalencia de enfermedades en una comunidad?', 0, 16),
(151, '¿Le llama la atención el estudio de la genética y el medio ambiente?', 0, 16),
(152, '¿Le interesan los aspectos psicológicos de un ser humano?', 0, 16),
(153, '¿Le interesaría estudiar las conductas de las personas en sus diferentes ámbitos de vida?', 0, 16),
(154, '¿Le llama la atención el estudio del hombre y su relación con su medio ambiente?', 0, 16),
(155, '¿En un futuro se ve como profesional de la vida alimenticia?', 0, 16),
(156, '¿Se ha interesado por el bienestar de la comunidad?', 0, 16),
(157, '¿Le llama la atención el estudio de los procesos vitales del ser humano?', 0, 16),
(158, '¿Considera interesante estudiar las etapas del desarrollo del individuo?', 0, 16),
(159, '¿Cree que es importante tener una buena vida alimenticia?', 0, 16),
(160, '¿Se interesa por conocer los distintos factores que intervienen en la salud del ser humano?', 0, 16),
(161, '¿Se ve como farmacéutico en un futuro?', 0, 16),
(162, '¿Le interesa el estudio de las propiedades de la materia?', 0, 17),
(163, '¿Hace parte de sus intereses estudiar la tabla periódica?', 0, 17),
(164, '¿Le llaman la atención las reacciones químicas?', 0, 17),
(165, '¿Considera interesantes los cambios en los estados de la materia?', 0, 17),
(166, '¿De acuerdo a su percepción el método científico es interesante?', 0, 17),
(167, '¿Le interesa el comportamiento de la energía?', 0, 17),
(168, '¿Considera importante el estudio de la física?', 0, 17),
(169, '¿Es importante para usted estudiar el tiempo y el espacio?', 0, 17),
(170, '¿Le interesa explicar los fenómenos naturales?', 0, 17),
(171, '¿Estudiaré los cambios físicos en los cuerpos?', 0, 17),
(172, '¿Le interesan los fenómenos que ocurren en el universo?', 0, 17),
(173, '¿Le interesa el razonamiento lógico?', 0, 17),
(174, '¿Son importantes los números en la vida del hombre?', 0, 17),
(175, '¿Le llaman la atención las figuras geométricas?', 0, 17),
(176, '¿Le interesa el uso de símbolos?', 0, 17),
(177, '¿Se considera bueno en la resolución de problemas matemáticos?', 0, 17),
(178, '¿Le interesa el desarrollo de la teoría científica?', 0, 17),
(179, '¿Le interesa la biología?', 0, 17),
(180, '¿Disfruta de los paisajes en su diario vivir?', 0, 17),
(181, '¿Prefiere explicar los fenómenos por método del método científico?', 0, 17);


ALTER TABLE `pregunta`
  ADD PRIMARY KEY (`Id_pregunta`),
  ADD KEY `PreguntaxIndicador` (`PregxIndi`);


ALTER TABLE `pregunta`
  MODIFY `Id_pregunta` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=182;


ALTER TABLE `pregunta`
  ADD CONSTRAINT `PreguntaxIndicador` FOREIGN KEY (`PregxIndi`) REFERENCES `indicador` (`Id_indicador`) ON UPDATE CASCADE;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
